config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

  resources :contacts,                only: [:index, :new, :create, :show]
  resources :reservations,            only: [:index, :new, :create, :show]
 
  namespace :admin do 
    root to: "reservations#index"
    resources :reservations,          only: [:index, :new, :create, :edit, :update, :destroy] do 
      member do 
        patch :cancel
      end
    end
    resources :room_types,            only: [:index, :new, :create, :edit, :update, :destroy]
    resources :room_images,           only: [:index, :new, :create, :edit, :update, :destroy]
    resources :rooms,                 only: [:index, :new, :create, :edit, :update, :destroy]
    resources :accounts,              only: [:index, :new, :create, :edit, :update, :destroy]
    resources :calendar,              only: [:index]
    resources :contacts,              only: [:index, :edit, :update, :destroy]
    resources :charts,                only: [:index]
  end

  namespace :api do 
    resources :charts, only: [:index] do
      collection do
        get :top_books
        get :sales
      end
    end
  end
end
 

app/controllers/admin/room_types_controller.rb
class Admin::RoomTypesController < Admin::BaseController
  def index
    @room_types = RoomType.all.paginate(:page => params[:page], :per_page => 4)
  end
  def new
    @room_type = RoomType.new
  end
  def create
    @room_type = RoomType.new room_type_params

    if @room_type.save
      flash[:notice] = "Save successfully"
      redirect_to admin_room_types_path
    else
      flash[:error] = "Please repeat"
      render 'new'
    end  
  end

  def edit
    @room_type = RoomType.find(params[:id])
  end

  def update
    @room_type = RoomType.find(params[:id])  
    if @room_type.update room_type_params
      redirect_to admin_room_types_path, notice: "Update successfully"
    else
      render 'edit', notice: "Update error"
    end
  end

  def destroy
    @room_type = RoomType.find(params[:id])
    @room_type.destroy
    redirect_to admin_room_types_path
  end

  private

  def room_type_params
    params.require(:room_type).permit(:name, :capacity, :price_per_night_cents, :price_per_month_cents, :description, :size, amenities: [])
  end
end

app/views/admin/room_types/_form.html.slim
section.admin_room_types-form
  .default-form
    .block_form
      .left
        = f.input :name
        = f.input :capacity
        = f.input :amenities
      .right  
        = f.input :price_per_night_cents
        = f.input :price_per_month_cents
        = f.input :size  
    = f.input :description
    .clearfix
      .pull-left
        = f.button :submit, class: "btn-primary-o"

app/views/admin/room_types/edit.html.slim
- breadcrumb :room_type_edit

.block
  .header
    .title
      h1 Edit Room Type
      p Please fill in room type information to edit room type.
  = simple_form_for @room_type, html: { class: 'show-required' }, url: admin_room_type_path(@room_type), as: :room_type do |f|
    = render 'form', room_type: @room_type, f: f

app/views/admin/room_types/index.html.slim
- breadcrumb :room_types

.block
  .header
    .title
      h1 Room_types
      p You can check ...
    .buttons
      = link_to "New Room Types", new_admin_room_type_path, class: "btn btn-primary-o"
  .clearfix        
  - @room_types.each do |r|
    .room_type
      h3 = r.name
      .details
        .left
          .detail
            b Capacity :
            p = r.capacity
          .detail
            b Price per night
            p = r.price_per_night
          .detail
            b Price per month
            p = r.price_per_month
        .right    
          .detail
            b Amenities:
            p = r.amenities.texts.join(", ")
          .detail
            b Size:
            p = "#{r.size} ft."
          b Description:
          p.description = simple_format r.description.truncate(200)
      .contols 
        = link_to 'Edit Room Type', edit_admin_room_type_path(r), class: 'btn btn-primary-o'
        = link_to 'Delete Room Type', admin_room_type_path(r), method: :delete, class: 'btn btn-primary-o'
  = will_paginate @reservations , :previous_label => '<<', :next_label => '>>', renderer: BootstrapPagination::Rails

app/views/admin/room_types/new.html.slim
- breadcrumb :room_type_create

.block
  .header
    .title
      h1 Create New Room Type
      p Please fill in room type information to create new room type.
  = simple_form_for @room_type, html: { class: 'show-required' }, url: admin_room_types_path do |f|
    = render 'form', room_type: @room_type, f: f