config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

  resources :contacts,                only: [:index, :new, :create, :show]
  resources :reservations,            only: [:index, :new, :create, :show]
 
  namespace :admin do 
    root to: "reservations#index"
    resources :reservations,          only: [:index, :new, :create, :edit, :update, :destroy] do 
      member do 
        patch :cancel
      end
    end
    resources :room_types,            only: [:index, :new, :create, :edit, :update, :destroy]
    resources :room_images,           only: [:index, :new, :create, :edit, :update, :destroy]
    resources :rooms,                 only: [:index, :new, :create, :edit, :update, :destroy]
    resources :accounts,              only: [:index, :new, :create, :edit, :update, :destroy]
    resources :calendar,              only: [:index]
    resources :contacts,              only: [:index, :edit, :update, :destroy]
    resources :charts,                only: [:index]
  end

  namespace :api do 
    resources :charts, only: [:index] do
      collection do
        get :top_books
        get :sales
      end
    end
  end
end
 

app/models/reservation.rb
class Reservation <  ApplicationRecord
  extend Enumerize

  belongs_to :room_type
  has_and_belongs_to_many :rooms, optional: true

  validates :name,            presence: true
  validates :contact_number,  presence: true
  validates :email,           presence: true, email: true
  validates :arrival_on,      presence: true
  validates :departure_on,    presence: true
  validates :no_of_persons,   presence: true
  validates :no_of_persons,   numericality: { greater_than: 0 }
  validates :no_of_rooms,     presence: true
  validates :no_of_rooms,     numericality: { greater_than: 0 }
  validates :status,          presence: true
  serialize :status, Array
  enumerize :status, in: [:booking, :expected, :cancelled], default: :expected
  validate :departure_date_is_after_arrival_date
  validate :room_availability

  def price_in(start_date, end_date)
    from = arrival_on
    to = departure_on
    if from < start_date
      from = start_date
    end

    if to > end_date
      to = end_date
    end

    return 0 if from > to
    return (to.to_date - from.to_date).to_i * room_type.price_per_night_cents
  end

  def price_reservation
    price_reservation = (departure_on - arrival_on).to_i * room_type.price_per_night_cents
    price_reservation
  end

  private

  def departure_date_is_after_arrival_date
    return if departure_on.blank? || arrival_on.blank?

    if departure_on < arrival_on
      errors.add(:departure_on, "cannot be before the arrival date") 
    end 
  end

  def room_availability
    rooms.each do |room|
      available = true

      room.reservations.each do |r|
        if (
          (r.id != id) &&
          !(departure_on <= r.arrival_on || r.departure_on <= arrival_on)
        )
          available = false
        end
      end

      errors.add(:room_ids, "#{room.name} is not available") if !available
    end
  end
end

app/controllers/admin/reservations_controller.rb
class Admin::ReservationsController < Admin::BaseController
  load_and_authorize_resource
  
  def index
    @reservations = Reservation.all
    @reservation_filter = ReservationFilter.new(@reservations, reservation_filter_params)
    @reservations = @reservation_filter.result.paginate(:page => params[:page], :per_page => 4)
  end
  def new
    @reservation = Reservation.new
  end
  def create
    @reservation = Reservation.new reservation_params

    if @reservation.save
      redirect_to admin_reservations_path, notice: "Save successfully"
    else
      render 'new', notice: "Please repeat"
    end  
  end

  def edit
    @reservation = Reservation.find(params[:id])
  end

  def update
    @reservation = Reservation.find(params[:id])  
    if @reservation.update reservation_params
      redirect_to admin_reservations_path, notice: "Update successfully"
    else
      render 'edit', notice: "Update error"
    end
  end

  def cancel
    @reservation = Reservation.find(params[:id])
    @reservation.status = :cancelled
    if @reservation.save
      redirect_to admin_reservations_path, notice: "Cancel successfully"
    else
      render 'edit', notice: "Cancel error"
    end  
  end

  private

  def reservation_params
    params.require(:reservation).permit(
      :name, 
      :contact_number, 
      :email, 
      :nric, 
      :arrival_on, 
      :departure_on, 
      :no_of_persons, 
      :no_of_rooms, 
      :remark, 
      :room_type_id,
      :status,
      room_ids: []
    )
  end

  def reservation_filter_params
    return {} if params[:reservation_filter].nil?

    params.require(:reservation_filter).permit(
      :keyword,
      :status
    )
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def new
    @reservations = Reservation.all
    @reservation = Reservation.new(reservation_params)
    @title = "Make Reservation"
    @room_types = RoomType.all
  end

  def create
    @room_types = RoomType.all
    @reservation = Reservation.new reservation_params
    @title = "Make Reservation"
    
    if @reservation.save
      redirect_to reservation_path(@reservation), notice: "Save successfully"
    else
      render 'new', notice: "Please repeat"
    end  
  end

  def show
    @reservation = Reservation.find(params[:id])
    @title = "Make Reservation"
  end

  private

  def reservation_params
    params.require(:reservation).permit(
      :name, 
      :contact_number, 
      :email, 
      :nric, 
      :arrival_on, 
      :departure_on, 
      :no_of_persons, 
      :no_of_rooms, 
      :remark, 
      :room_type_id, 
      room_ids: []
    )
  end
end

app/views/admin/reservations/_form.html.slim
section.admin_reservations-form
  .default-form.show-required
    .block_form
      .left
        = f.input :name
        = f.input :email, :input_html => { :type => "email" }
        = f.input :contact_number
        = f.input :nric
        = f.input :status
      .right  
        = f.input :arrival_on, :as => :date_picker
        = f.input :departure_on, :as => :date_picker
        = f.input :no_of_persons
        = f.input :no_of_rooms
    = f.input :remark
    .block_form
      .left
        = f.association :room_type
      .right  
        = f.association :rooms
    .clearfix
      .pull-left
        = f.button :submit, class: "btn-primary-o"

app/views/admin/reservations/edit.html.slim
- breadcrumb :reservation_edit

.block
  .header
    .title
      h1 Edit Reservation
      p Please fill in customer’s information to edit update reservation.
  = simple_form_for @reservation, url: admin_reservation_path(@reservation), as: :reservation do |f|
    = render 'form', reservation: @reservation, f: f

app/views/admin/reservations/index.html.slim
- breadcrumb :reservations

.block
  .header
    .title
      h1 Reservations
      p You can check for reservation and edit them here. Or you can create new reservation too.
    .buttons
      = link_to "New Reservation", new_admin_reservation_path, class: "btn btn-primary-o"
  .search
    h2 Search
    = simple_form_for @reservation_filter, url: '', method: :get do |f|
      = f.input :keyword, label: false
      = f.input :status, collection: Reservation.status.options
      = f.button :submit, 'Search', class: "btn-primary-o"
  .clearfix        
  - @reservations.includes(:rooms).each do |r|
    .reservation
      h3 = r.name
      .details
        .left
          .detail
            b Contact Number:
            p = r.contact_number
          .detail
            b Email:
            p = r.email
          .detail
            b NRIC:
            p = r.nric
          .detail
            b Room Type:
            p = r.room_type.name
          .detail
            b Remark:
            = simple_format r.remark.truncate(200)
        .right    
          .detail
            b Arrival Date:
            p = r.arrival_on
          .detail
            b Departure Date:
            p = r.departure_on
          .detail
            b No. of Rooms:
            p = r.no_of_rooms
          .detail
            b No. of Persons:
            p = r.no_of_persons
          .detail
            b Total Price:
            p = r.price_reservation
          .detail
            b Room Selected: 
            p = r.rooms.map(&:name).join(", ")
          .detail
            b Status:
            p = r.status_text
      .contols
        = link_to 'Edit Reservation', edit_admin_reservation_path(r), class: 'btn btn-primary-o'
        - if !r.status.cancelled?
          = link_to 'Cancel Reservation', cancel_admin_reservation_path(r), method: :patch, class: 'btn btn-primary-o'
  = will_paginate @reservations , :previous_label => '<<', :next_label => '>>', renderer: BootstrapPagination::Rails  



  

app/views/admin/reservations/new.html.slim
- breadcrumb :reservation_create

.block
  .header
    .title
      h1 Create New Reservation
      p Please fill in customer’s information to create new reservation.
  = simple_form_for @reservation, html: { autocomplete: 'off' }, url: admin_reservations_path, as: :reservation do |f|
    = render 'form', reservation: @reservation, f: f