config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

  resources :contacts,                only: [:index, :new, :create, :show]
  resources :reservations,            only: [:index, :new, :create, :show]
 
  namespace :admin do 
    root to: "reservations#index"
    resources :reservations,          only: [:index, :new, :create, :edit, :update, :destroy] do 
      member do 
        patch :cancel
      end
    end
    resources :room_types,            only: [:index, :new, :create, :edit, :update, :destroy]
    resources :room_images,           only: [:index, :new, :create, :edit, :update, :destroy]
    resources :rooms,                 only: [:index, :new, :create, :edit, :update, :destroy]
    resources :accounts,              only: [:index, :new, :create, :edit, :update, :destroy]
    resources :calendar,              only: [:index]
    resources :contacts,              only: [:index, :edit, :update, :destroy]
    resources :charts,                only: [:index]
  end

  namespace :api do 
    resources :charts, only: [:index] do
      collection do
        get :top_books
        get :sales
      end
    end
  end
end
 

app/models/room_image.rb
class RoomImage <  ApplicationRecord
  belongs_to :room_type

  has_attached_file :image, styles: { medium: "850x900>", thumb: "400x320>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/admin/room_images_controller.rb
class Admin::RoomImagesController < Admin::BaseController
  def index
    @room_images = RoomImage.all.paginate(:page => params[:page], :per_page => 4)
  end

  def new
    @room_image = RoomImage.new
  end

  def create
    @room_image = RoomImage.new room_image_params

    if @room_image.save
      redirect_to admin_room_images_path, notice: "Save successfully"
    else
      render 'new', notice: "Please repeat"
    end  
  end

  def edit
    @room_image = RoomImage.find(params[:id])
  end

  def update
    @room_image = RoomImage.find(params[:id])  
    if @room_image.update room_image_params
      redirect_to admin_room_images_path, notice: "Update successfully"
    else
      render 'edit', notice: "Update error"
    end
  end

  def destroy
    @room_image = RoomImage.find(params[:id])
    @room_image.destroy
    redirect_to admin_room_images_path
  end

  private

  def room_image_params
    params.require(:room_image).permit(:image, :room_type_id)
  end
end

app/views/admin/room_images/_form.html.slim
section.admin_room_images-form
  .default-form
    .block_form
      = f.input :image, as: :file
      = f.association :room_type
    .clearfix
      .pull-left
        = f.button :submit, class: "btn-primary-o"

app/views/admin/room_images/edit.html.slim
- breadcrumb :room_image_create

.block
  .header
    .title
      h1 Edit Room Image
      p Please choose file.
  = simple_form_for @room_image, url: admin_room_image_path(@room_image) do |f|
    = render 'form', room_image: @room_image, f: f

app/views/admin/room_images/index.html.slim
- breadcrumb :room_images

.block
  .header
    .title
      h1 Room Images
      p You can check ...
    .buttons
      = link_to "New Room Image", new_admin_room_image_path, class: "btn btn-primary-o"
  .clearfix        
  - @room_images.each do |r|
    .room_image
      h3 = r.room_type.name
      .details
          .detail
            b Image :
            p = image_tag r.image.url(:medium)
      .contols 
        = link_to 'Edit Room Image', edit_admin_room_image_path(r), class: 'btn btn-primary-o'
        = link_to 'Delete Room Image', admin_room_image_path(r), method: :delete, class: 'btn btn-primary-o'
  = will_paginate @reservations , :previous_label => '<<', :next_label => '>>', renderer: BootstrapPagination::Rails

app/views/admin/room_images/new.html.slim
- breadcrumb :room_image_create

.block
  .header
    .title
      h1 Create New Room Image
      p Please choose file.
  = simple_form_for @room_image, url: admin_room_images_path do |f|
    = render 'form', room_image: @room_image, f: f