config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

  resources :contacts,                only: [:index, :new, :create, :show]
  resources :reservations,            only: [:index, :new, :create, :show]
 
  namespace :admin do 
    root to: "reservations#index"
    resources :reservations,          only: [:index, :new, :create, :edit, :update, :destroy] do 
      member do 
        patch :cancel
      end
    end
    resources :room_types,            only: [:index, :new, :create, :edit, :update, :destroy]
    resources :room_images,           only: [:index, :new, :create, :edit, :update, :destroy]
    resources :rooms,                 only: [:index, :new, :create, :edit, :update, :destroy]
    resources :accounts,              only: [:index, :new, :create, :edit, :update, :destroy]
    resources :calendar,              only: [:index]
    resources :contacts,              only: [:index, :edit, :update, :destroy]
    resources :charts,                only: [:index]
  end

  namespace :api do 
    resources :charts, only: [:index] do
      collection do
        get :top_books
        get :sales
      end
    end
  end
end
 

app/views/admin/shared/_menu.html.slim
section.admin-shared-menu
  = icon('fas', 'bars', id: "sidebarBtn")

javascript:
  DemoCssFisrtProject.shared.menu.init()

app/views/admin/shared/_sidebar.html.slim
section.admin-shared-sidebar#sidebar
  .logo-panel
    = link_to '/admin', class: "logo-admin"
      = image_tag("admin/admin-panel.png", alt: "Image error", title: "Admin panel")

  ul
    = active_link_to admin_reservations_path, active: /^(\/admin\/?$|\/admin\/reservations)/, :wrap_tag => :li
      = icon('fas', 'home')
      | Reservations
    - if can? :index, RoomType  
      = active_link_to admin_room_types_path, :wrap_tag => :li
        = icon('fas', 'igloo')
        | Room types
      = active_link_to admin_rooms_path, :wrap_tag => :li
        = icon('fas', 'igloo')
        | Rooms
      = active_link_to admin_room_images_path, :wrap_tag => :li
        = icon('fas', 'igloo')
        | Room images
      = active_link_to admin_calendar_index_path, :wrap_tag => :li
        = icon('far', 'calendar-alt')
        | Calendar
      = active_link_to admin_accounts_path, :wrap_tag => :li
        = icon('far', 'calendar-alt')
        | Account
      = active_link_to admin_charts_path, :wrap_tag => :li
          = icon('far', 'chart-bar')
          | Reports
    li  
      = icon('fas', 'sign-out-alt', class: 'fa-rotate-45')
      = link_to('Logout', destroy_user_session_path, method: :delete)